// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3sskiKlKBPEjXq6jaBvSXuoCvexCJmjY',
    appId: '1:144539675688:web:ccc187e09d9a951df0d91d',
    messagingSenderId: '144539675688',
    projectId: 'my-project-f451a',
    authDomain: 'my-project-f451a.firebaseapp.com',
    storageBucket: 'my-project-f451a.firebasestorage.app',
    measurementId: 'G-HS22Q9QR4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUOsGkoHA4E1obqLkdG83GFz16Izc4DQk',
    appId: '1:144539675688:android:5d5f948be9e6c84cf0d91d',
    messagingSenderId: '144539675688',
    projectId: 'my-project-f451a',
    storageBucket: 'my-project-f451a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCckIfpnDCljVC0Hy_IUcoSodiXTZumD7k',
    appId: '1:144539675688:ios:e35368891765feb0f0d91d',
    messagingSenderId: '144539675688',
    projectId: 'my-project-f451a',
    storageBucket: 'my-project-f451a.firebasestorage.app',
    iosBundleId: 'com.example.flutterLessons',
  );
}
